---
# tasks file for ansible-role-protonvpn
#
# @see https://protonvpn.com/support/official-ubuntu-vpn-setup/
# @see https://protonvpn.com/support/official-linux-vpn-debian/

- name: "Proton VPN | check if app is already installed."
  ansible.builtin.shell: "command -v {{ pvpn__binary_name }}"
  register: "pvpn__binary_exists"

- name: "Proton VPN | debug binary existence."
  debug:
    var: "pvpn__binary_exists"

- name: "Proton VPN | download and install Proton VPN."
  include_tasks:
    file: "install.yaml"
  when:
    - "pvpn__binary_exists.rc != 0"
    - "pvpn__state == 'present'"
