---
# uninstall tasks file for ansible-role-protonvpn

# Uninstall
# sudo apt autoremove "protonvpn*" proton-vpn-gnome-desktop
#
# Check for existing connections after uninstall.
# nmcli --terse --fields name connection show --active

- name: "Proton VPN | find any remaining Proton VPN connections"
  command: "nmcli --terse --fields name connection show --active"
  register: "pvpn__active_connections"

- name: "Proton VPN | terminate any remaining Proton VPN connections"
  command: "nmcli connection delete {{ connection }}"
  loop: "{{ pvpn__active_connections.stdout_lines|regex_findall('^pvpn') }}"
  loop_control:
    loop_var: "connection"

- name: "Proton VPN | uninstall apt package."
  apt:
    name:
      - "protonvpn*"
      - "{{ pvpn__package_name }}"
    state: "absent"

- name: "Proton VPN | remove apt repository."
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ pvpn__apt_repository_key_path }}] {{ pvpn__apt_repository_url }}  {{ pvpn__apt_repository_codename }} {{ pvpn__apt_repository_component }}"
    state: "absent"

- name: "Proton VPN | remove repo public key."
  file:
    path: "{{ pvpn__apt_repository_key_path }}"
    state: "absent"
